---
title: "Project and Time Management"
description: |
 Advice for managing your project, and your time
number-sections: true
about:
  template: marquee
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com/scompbiol
    - icon: github
      text: Github
      href: https://github.com/sipbs-compbiol
    - icon: envelope
      text: Email
      href: mailto:leighton.pritchard@strath.ac.uk
html:
  anchor-sections: true
---

This may be your first time working on a scientific project or set of experiments at this kind of scale. The amount and variety of work required can seem overwhelming, especially if the topics and techniques are new. The need to keep a larger-level project and its goals in mind while focusing on a smaller subtask or single experiment can also be tricky, but does get easier with practice.

::: {.callout-caution}
These articles come from external sources and are opinions. You will find a range of opinions within the group, as well as online. Some approaches are objectively better than others, and some are personal preference. Find what works for you, and **discussion is encouraged**!
:::

## Data and Project Management

These Notebooks on data and project management were prepared by Dr. Pritchard and Dr. Feeney for the 2022 session of BM432

- [Project management guidelines](https://sipbs-compbiol.github.io/BM432/notebooks/03-data_management_workshop.html) 
    - [01-Data Analysis in the Research Cycle](https://sipbs-compbiol.github.io/BM432/notebooks/03-01-data_analysis.html)
    - [02-Data and Project Management](https://sipbs-compbiol.github.io/BM432/notebooks/03-02-project_management.html)
    - [03-Reproducibility, Replicability, and FAIR Guidelines](https://sipbs-compbiol.github.io/BM432/notebooks/03-03-reproducibility.html)
    - [04-Keeping a Lab Notebook to Document Your Project](https://sipbs-compbiol.github.io/BM432/notebooks/03-04-keeping_a_lab_notebook.html)
    - [05-Reference Management](https://sipbs-compbiol.github.io/BM432/notebooks/03-05-reference_management.html)
    - [06-How to Use Reference Management Software](https://sipbs-compbiol.github.io/BM432/notebooks/03-06-using_a_reference_manager.html)

## Laboratory Notebooks: Advice

- [A Quick Guide to Organizing Computational Biology Projects](https://doi.org/10.1371/journal.pcbi.1000424) 
  - _My favourite introduction to the topic. It clearly lays out a template and a rationale for each decision - LP_
- [How to Keep a Lab Notebook for Bioinformatic Analyses](https://blog.addgene.org/how-to-keep-a-lab-notebook-for-bioinformatic-analyses) 
  - _A guest blog at AddGene which makes some choices I would question. They're probably fine for one small project, but I'd worry about scaling up, and lack of clarity in the longer term - LP_
- [Ten Simple Rules for a Computational Biologist's Laboratory Notebook](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004385) 
  - _Overall sound advice, but short on recommending specific solutions - LP_
- [10 File Management Tips to Keep Your Electronic Files Organized](https://www.liveabout.com/computer-file-management-tips-2948083) 
  - _Good general advice, and not only for bioinformatics projects - LP_
- [How to keep a lab notebook](https://www.science.org/content/article/how-keep-lab-notebook) 
  - _First-hand experience in quotes from a number of scientists. Learn from their fails - LP_ 
- [10 Tips For Organizing Your Lab Book](https://bitesizebio.com/11068/10-tips-for-organizing-your-lab-book/) 
  - _Very lab-focused, but good general points - LP_

## Time and Project Management: Advice

- [8 Time Management Tips for Students](https://summer.harvard.edu/blog/8-time-management-tips-for-students/)
  - _Really good general advice, from Harvard - LP_
- [Kanban boards](https://en.wikipedia.org/wiki/Kanban_board)
  - _Kanban is a flexible way to manage projects that allows for rearrangement and rescheduling in the middle of the work. It doesn't require any particular tool or software (I used to use sticky notes), but Trello does a good job of this - LP_
- [Pomodoro Technique](https://en.wikipedia.org/wiki/Pomodoro_Technique)
  - _I use the Pomodoro technique (with BeFocused, see below) to help me focus when I need to get through long writing tasks. I find it most useful to avoid burning out on a large piece of work - LP_

## Time and Project Management: Resources

- [Trello](https://trello.com/)
  - A widely-used project management tool, but tailored towards teams. It probably does more than you need - LP_
- [Asana](https://asana.com/)
  - Seems to be similar to Trello. I haven't used it, myself - LP_
- [Benchling](https://www.benchling.com/)
  - An electronic lab notebook platform that is widely used in industry. Academic use is free, and having it on your CV can be an advantage, so I'm told - LP_
- [Pomodoro Timer](https://pomofocus.io/)
  - Free timer for Pomodoro. Just does the timing, which may be all you need - LP_
- [BeFocused](https://apps.apple.com/us/app/be-focused-focus-timer/id973130201)
  - Pomodoro timer with additional project management and time categorisation features. It's the tool I use - LP_
- [Forest](https://www.forestapp.cc/)
  - A focusing app. I hear good things but I don't use it - LP_
- [EverNote](https://evernote.com/)
  - Note-taking app. I know people who love it, but it didn't grab me - LP_

